[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "lab",
    "models",
    "sdk",
    "plugins/demog",
    "plugins/econ",
    "plugins/gov"
]

[workspace.dependencies]
models = { path = "models" }
sdk = { path = "sdk" }
core = { path = "core" }