[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "sdk",
    "models",
    "lab",
    "plugins/demog",
    "plugins/econ",
    "plugins/gov",
]

[workspace.dependencies]
models = { path = "models" }
sdk = { path = "sdk" }